#开发环境
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# jpa:
#    hibernate:
#      ddl-auto: update //自动更新
#    show-sql: true  //日志中显示sql语句

#jpa.hibernate.ddl-auto是hibernate的配置属性，其主要作用是：自动创建、更新、验证数据库表结构。该参数的几种配置如下：
#    ·create：每次加载hibernate时都会删除上一次的生成的表，然后根据你的model类再重新来生成新表，哪怕两次没有任何改变也要这样执行，这就是导致数据库表数据丢失的一个重要原因。
#    ·create-drop：每次加载hibernate时根据model类生成表，但是sessionFactory一关闭,表就自动删除。
#    ·update：最常用的属性，第一次加载hibernate时根据model类会自动建立起表的结构（前提是先建立好数据库），以后加载hibernate时根据model类自动更新表结构，即使表结构改变了但表中的行仍然存在不会删除以前的行。要注意的是当部署到服务器后，表结构是不会被马上建立起来的，是要等应用第一次运行起来后才会。
#    ·validate：每次加载hibernate时，验证创建数据库表结构，只会和数据库中的表进行比较，不会创建新表，但是会插入新值。

 #@Entity	声明类为实体或表。
 #@Table	声明表名。
 #@Basic	指定非约束明确的各个字段。
 #@Embedded	指定类或它的值是一个可嵌入的类的实例的实体的属性。
 #@Id	指定的类的属性，用于识别（一个表中的主键）。
 #@GeneratedValue	指定如何标识属性可以被初始化，例如自动、手动、或从序列表中获得的值。
 #@Transient	指定的属性，它是不持久的，即：该值永远不会存储在数据库中。
 #@Column	指定持久属性栏属性。
 #@SequenceGenerator	指定在@GeneratedValue注解中指定的属性的值。它创建了一个序列。
 #@TableGenerator	指定在@GeneratedValue批注指定属性的值发生器。它创造了的值生成的表。
 #@AccessType	这种类型的注释用于设置访问类型。如果设置@AccessType（FIELD），则可以直接访问变量并且不需要getter和setter，但必须为public。如果设置@AccessType（PROPERTY），通过getter和setter方法访问Entity的变量。
 #@JoinColumn	指定一个实体组织或实体的集合。这是用在多对一和一对多关联。
 #@UniqueConstraint	指定的字段和用于主要或辅助表的唯一约束。
 #@ColumnResult	参考使用select子句的SQL查询中的列名。
 #@ManyToMany	定义了连接表之间的多对多一对多的关系。
 #@ManyToOne	定义了连接表之间的多对一的关系。
 #@OneToMany	定义了连接表之间存在一个一对多的关系。
 #@OneToOne	定义了连接表之间有一个一对一的关系。
 #@NamedQueries	指定命名查询的列表。
 #@NamedQuery	指定使用静态名称的查询。
logging:
  level:
    root: info
    com.lrm: debug
  file:
    name: log/blog-dev.log
server:
  port: 8002
